---
root: true
env:
  browser: true
  es2020: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  createDefaultProgram: true
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 2
  react/jsx-wrap-multilines: 0
  import/prefer-default-export: 0
  import/order: 0
  '@typescript-eslint/no-use-before-define': [ 2, { variables: false } ]
  react/require-default-props: 0
  react/prop-types: 0
  react/jsx-curly-newline: 0
  arrow-body-style: 0
extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint