basePath: /api
definitions:
  entity.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  handler.checkAuthResponse:
    properties:
      user:
        $ref: '#/definitions/entity.User'
    type: object
  handler.errResponse:
    properties:
      message:
        type: string
    type: object
  handler.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.loginResponse:
    properties:
      user:
        $ref: '#/definitions/entity.User'
    type: object
  handler.optionResponse:
    properties:
      id:
        type: string
      sequence:
        type: integer
      title:
        type: string
      vote_count:
        type: integer
    type: object
  handler.questionResponse:
    properties:
      id:
        type: string
      options:
        items:
          $ref: '#/definitions/handler.optionResponse'
        type: array
      sequence:
        type: integer
      title:
        type: string
    type: object
  handler.respondentCreateRequest:
    properties:
      email:
        type: string
      name:
        type: string
      option_ids:
        items:
          type: string
        type: array
      survey_id:
        type: string
    type: object
  handler.respondentResponse:
    properties:
      id:
        type: string
      survey_id:
        type: string
    type: object
  handler.surveyListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/handler.surveyResponse'
        type: array
      total_count:
        type: integer
    type: object
  handler.surveyPublisher:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  handler.surveyResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      publisher:
        $ref: '#/definitions/handler.surveyPublisher'
      questions:
        items:
          $ref: '#/definitions/handler.questionResponse'
        type: array
      title:
        type: string
    type: object
  handler.surveySaveRequest:
    properties:
      questions:
        items:
          properties:
            options:
              items:
                properties:
                  title:
                    type: string
                type: object
              type: array
            title:
              type: string
          type: object
        type: array
      title:
        type: string
    type: object
  handler.userCreateRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handler.userCreateResponse:
    properties:
      user:
        $ref: '#/definitions/entity.User'
    type: object
host: localhost:8080
info:
  contact: {}
  description: Server caller for survey backend API.
  title: Survey backend API
  version: "0.1"
paths:
  /check_auth:
    get:
      operationId: check-auth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.checkAuthResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Check user authentication state
  /login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: Authentication data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.loginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.errResponse'
      summary: Authenticate User
  /logout:
    post:
      operationId: logout
      responses:
        "204":
          description: ""
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Clear user authentication state
  /respondents:
    get:
      operationId: respondent-list
      parameters:
      - description: Answered user's email address
        in: query
        name: email
        required: true
        type: string
      - description: Answered user's name
        in: query
        name: name
        required: true
        type: string
      - description: Comma separated ids of survey
        in: query
        name: surveyIds
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.respondentResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errResponse'
      summary: List of respondent
    post:
      consumes:
      - application/json
      operationId: respondent-create
      parameters:
      - description: Respondent data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.respondentCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.respondentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errResponse'
      summary: Create respondent for survey
  /surveys:
    get:
      operationId: survey-list
      parameters:
      - default: 1
        description: What pages of survey to get
        in: query
        name: page
        required: true
        type: integer
      - default: 20
        description: How many surveys to get
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.surveyListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errResponse'
      summary: List of survey
    post:
      consumes:
      - application/json
      operationId: survey-create
      parameters:
      - description: Survey data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.surveySaveRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.surveyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Create survey
  /surveys/{id}:
    delete:
      operationId: survey-delete
      parameters:
      - description: Survey ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: ""
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.errResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete survey
    get:
      operationId: survey-show
      parameters:
      - description: Survey ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.surveyResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errResponse'
      summary: Detail of survey
    put:
      consumes:
      - application/json
      operationId: survey-update
      parameters:
      - description: Survey data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.surveySaveRequest'
      - description: Survey ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.surveyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.errResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Update survey
  /users:
    post:
      consumes:
      - application/json
      operationId: user-create
      parameters:
      - description: User data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.userCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.userCreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.errResponse'
      summary: Create user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
