version: "3"
services:
  survey-server:
    image: survey-server:latest
    command: ["/app/bin/survey-server"]
    environment:
      SECRET_KEY: BH4G7yzUgP\xanm
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: survey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ALLOWED_ORIGINS: http://localhost:3000
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
  test:
    image: survey-server-base:latest
    environment:
      SECRET_KEY: BH4G7yzUgP\xanm
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: survey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ALLOWED_ORIGINS: http://localhost:3000
    volumes:
      - .:/go/src/github.com/t-tiger/survey/server
      - go_pkg:/go/pkg
      - go_build:/root/.cache/go-build
    tty: true
    stdin_open: true
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  go_pkg:
    driver: local
  go_build:
    driver: local
